[customizations.installer.kickstart]
contents = """
text
zerombr
ignoredisk --only-use=disk/by-id/nvme-WD_Red_SN700_1000GB_22012N800363
clearpart --initlabel --disklabel=gpt --drives=disk/by-id/nvme-WD_Red_SN700_1000GB_22012N800363 --all
autopart --type=lvm --fstype=xfs --noswap --nohome
network --bootproto=dhcp --device=link --activate --onboot=on
timezone UTC
rootpw --lock
user --name=core --homedir=/var/home/core --password="password" --plaintext --groups=wheel --shell=/usr/bin/fish
bootloader --append="console=tty0 console=ttyS0,115200"
%post --interpreter=/usr/bin/bash
# Changing default shell for root
chsh --shell /usr/bin/fish root

# Configures passwordless sudo for wheel group
cat > /etc/sudoers.d/sudo-group <<'EOF'
%wheel  ALL=(ALL)       NOPASSWD: ALL
EOF
chmod 440 /etc/sudoers.d/sudo-group

# NUT
cat > /etc/udev/rules.d/99-nut-eaton.rules <<'EOF'
SUBSYSTEM=="usb", ATTR{idVendor}=="0463", ATTR{idProduct}=="ffff", MODE="0660", GROUP=101
EOF

# Orches
mkdir -p /var/lib/orches /etc/containers/systemd
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Localization",
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Timezone",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Network",
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Subscription",
]
